title: ABHAY
author: abhay
email: your-a25abhinav@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am abhay.Student of B.sc.

# social links
twitter_username: a25abhinav # DO NOT include the @ character, or else the build will fail!
github_username:  A255abhay # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
